name: metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          config_timezone: Europe/Berlin

          plugin_achievements: yes
          plugin_habits: yes
          plugin_introduction: yes
          plugin_languages: yes
          plugin_licenses: yes
          plugin_lines: yes
          plugin_reactions: yes
